language: bash
services: docker
env:
  - DISTRO=alpine VARIANT=cli
  - DISTRO=alpine VARIANT=fpm
  - DISTRO=debian-jessie VARIANT=cli
  - DISTRO=debian-jessie VARIANT=fpm
install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images
before_script:
  - docker -v
  - image="realpage/php:${DISTRO}${VARIANT:+-$VARIANT}"
  - echo "${DISTRO}/${VARIANT:-.}"
  - echo "${DISTRO}${VARIANT:+-$VARIANT}"
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script:
  - docker build -t "$image" "${DISTRO}/${VARIANT:-.}"
  - ~/official-images/test/run.sh "$image"
  - docker images
  # build and push all variations of images
  - if [[ $TRAVIS_PULL_REQUEST = false && $TRAVIS_BRANCH == 'master' ]]; then bash build.sh ; fi
notifications:
  slack:
    secure: ${SLACK_TOKEN}
