language: bash
services: docker
env:
 - VARIANT=cli
 - VARIANT=fpm
install:
 - git clone https://github.com/docker-library/official-images.git ~/official-images
before_script:
 - docker -v
 - image="realpage/php:${VARIANT}-latest"
 - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script:
 - docker build -t "$image" -f "${VARIANT}/Dockerfile" .
 - ~/official-images/test/run.sh "$image"
 - docker images
before_deploy:
 # Extract the version components out of a `v12.34.56` or `12.34.56` version string (only works if this is a semantically versioned tag)
 - IFS=. read MAJOR MINOR PATCH <<< "${TRAVIS_TAG#v}"
 - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
deploy:
 provider: script
 script: docker push "$image" && docker tag "$image" "realpage/php:${MAJOR}-${VARIANT}" && docker push "realpage/php:${MAJOR}-${VARIANT}" && docker tag "$image" "realpage/php:${MAJOR}.${MINOR}-${VARIANT}" && docker push "realpage/php:${MAJOR}.${MINOR}-${VARIANT}" && docker tag "$image" "realpage/php:${MAJOR}.${MINOR}.${PATCH}-${VARIANT}" && docker push "realpage/php:${MAJOR}.${MINOR}.${PATCH}-${VARIANT}"
 skip_cleanup: false
 on:
   tags: true